[package]
name = "scrypto_math"
version = "0.0.1"
edition = "2021"
license = "MIT"
description = "Math library extending Radix Scrypto with more advanced mathematical operations"
repository = "https://github.com/ociswap/scrypto-math"

[dependencies]
utils = { git = "https://github.com/radixdlt/radixdlt-scrypto", tag = "v0.10.0", version = "0.10.0" }
radix-engine-common = { git = "https://github.com/radixdlt/radixdlt-scrypto", tag = "v0.10.0", version = "0.10.0" }
num-bigint = "0.4.3"
num-traits = "0.2.15"

[dev-dependencies]
paste = "1.0.13"
